name: RPGFramework
version: 0.0.1
main: io.github.math0898.rpgframework.main
api-version: 1.17
authors: [ Sugaku ]
description: The main framework plugin used for all of Math0898/Sugaku's RPG  plugins.
