plugins {
    id 'java'
    id("io.freefair.lombok") version "9.2.0"
}

group = 'io.github.math0898'
version = '4.0.0-dev'
var filename = "RPGFramework.jar"

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "codemc-repo"
        url = "https://repo.codemc.io/repository/maven-public/"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.1.build.+")
    testImplementation(platform("org.junit:junit-bom:5.13.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-junit-jupiter:5.12.0")
    testImplementation("org.mockito:mockito-inline:5.2.0")
    implementation "org.jetbrains:annotations:26.1.0"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveFileName = filename;
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.register('testLocal') {
    onlyIf = { true }
    doLast {
        exec {
            ignoreExitValue = true
            commandLine "./test_local.sh", filename;
        }
    }
}

tasks.register('publishServer') {
    onlyIf = { true }
    doLast {
        exec {
            ignoreExitValue = true
            commandLine "./publish_server.sh", filename
        }
    }
}
